api = "0.2"

[buildpack]
id = "heroku/ruby"
version = "0.0.1"
name = "Ruby"
ruby_version = "2.7.1"

  [publish.Ignore]
  files = [
    "spec/"
  ]

  [[publish.Vendor]]
  # get tokens for logging build tokens
  url = "https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz"
  dir = "."
  files = ["./.env"]
  [[publish.Vendor]]
  url = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz"
  dir = "vendor/ruby/cedar-14"
  [[publish.Vendor]]
  url = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz"
  dir = "vendor/ruby/heroku-16"
  [[publish.Vendor]]
  url = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz"
  dir = "vendor/ruby/heroku-18"
  [[publish.Vendor]]
  url = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz"
  dir = "vendor/ruby/heroku-20"

[[stacks]]
id = "heroku-18"
